### ISSUE TITLE
Memory leak when used with bundler/setup and accessing job.stats["tube"]

### ISSUE THREAD

**Issue by dkam** [kr/beanstalk-client-ruby#11] opened 2012-03-02 12:48 UTC
Hey there,

I use beanstalk in rails and within an external daemon which processes jobs in a queue. I use

```
job.stats["tube"] 
```

to determine which tube a job came from.  Is this a valid operation?  

When used with 'bundler/setup', memory usage slowly grows and isn't released.  

Running the code below:
- without accessing job.stats["tube"]     and excluding 'bundler/setup': 15.7 MB
- including accessing job.stats["tube"]  and excluding 'bundler/setup': 18.8 MB
- without accessing job.stats["tube"]      and including 'bundler/setup': 23.9 MB
- including accessing job.stats["tube"]  and including 'bundler/setup': 567MB 

``` ruby
require "bundler/setup"
require 'beanstalk-client'                                                                                                                

beanstalk = Beanstalk::Pool.new(["localhost:11300"])

beanstalk.use "ping"

# Load up beanstalkd

50000.times {|i| beanstalk.put("PING! - #{i}")}

# Grab out entries and delete them.

beanstalk.watch("ping")
job = nil

loop do
  begin
    job = beanstalk.reserve(1)
  rescue Beanstalk::TimedOut
    puts "So bored."
    retry
  end

  # The following access to job.stats["tube"] causes the issue - but only when used with bundler.
  puts job.stats["tube"]
  puts "Deleting job : #{job.body}"
  job.delete
end
```

Anyone else seen this?

**Comment by dkam** [comment] 2012-03-02 13:08
Actually, accessing anything which calls the stats method on job, including job.pri and job.age also trigger the issue with bundler.

**Comment by jmalcolm** [comment] 2012-08-30 00:45
Actually, I believe this was caused by the memory leak problem in ruby's YAML.load. I was able to fix this by explicitly adding the psych gem. The latest psych gem replaces the default yaml loader and this problem went away.

**Comment by kr** [comment] 2012-08-30 06:19
Good to know. I'm closing this, but if anyone thinks it's a
problem specific to beanstalk-client-ruby, please reopen.

**Closed as completed by kr** 2012-08-30 06:19 UTC
